"""
Validate outputs generated by the bundled end-to-end sample run.

This script validates software/reproducibility contracts rather than
clinical validity. It is intended to be executed after the master
recommender pipeline has been run on the bundled sample datasets.

Example
-------
PYTHONPATH=. python scripts/validate_sample_run.py \
    --output-dir /tmp/preeclampsia_sample_run
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List

import numpy as np
import pandas as pd


EXPECTED_CSV_FILES = [
    "df_db_vec.csv",
    "df_syn_vec.csv",
    "protocol_score_df.csv",
    "recs_raw_df.csv",
    "recs_final_df.csv",
    "patient_profiles_df.csv",
    "clinical_recs_df.csv",
]

SUMMARY_FILE = "artifacts_summary.json"


def validate_required_files(output_dir: Path) -> None:
    """Validate that all expected sample-run artifacts exist."""
    expected_files = EXPECTED_CSV_FILES + [SUMMARY_FILE]

    missing = [
        filename
        for filename in expected_files
        if not (output_dir / filename).is_file()
    ]

    if missing:
        raise AssertionError(
            "Missing expected output artifacts: "
            + ", ".join(sorted(missing))
        )


def load_outputs(output_dir: Path) -> Dict[str, pd.DataFrame]:
    """Load generated CSV outputs."""
    return {
        Path(filename).stem: pd.read_csv(output_dir / filename)
        for filename in EXPECTED_CSV_FILES
    }


def load_summary(output_dir: Path) -> Dict:
    """Load artifacts_summary.json."""
    with open(output_dir / SUMMARY_FILE, "r", encoding="utf-8") as file:
        return json.load(file)


def validate_nonempty_outputs(
    outputs: Dict[str, pd.DataFrame],
) -> None:
    """Ensure core generated outputs are not empty."""
    for name, df in outputs.items():
        if df.empty:
            raise AssertionError(f"Generated output is empty: {name}")


def validate_summary_shapes(
    outputs: Dict[str, pd.DataFrame],
    summary: Dict,
) -> None:
    """Check that JSON-recorded shapes match generated CSV files."""
    recorded_shapes = summary.get("shapes")

    if not isinstance(recorded_shapes, dict):
        raise AssertionError(
            "artifacts_summary.json does not contain a valid 'shapes' object."
        )

    for name, expected_shape in recorded_shapes.items():
        if name not in outputs:
            raise AssertionError(
                f"Summary contains unknown dataframe output: {name}"
            )

        actual_shape = list(outputs[name].shape)

        if actual_shape != expected_shape:
            raise AssertionError(
                f"Shape mismatch for {name}: "
                f"summary={expected_shape}, actual={actual_shape}"
            )


def validate_patient_coverage(
    outputs: Dict[str, pd.DataFrame],
) -> None:
    """Validate patient coverage across review outputs."""
    synthetic = outputs["df_syn_vec"]
    profiles = outputs["patient_profiles_df"]
    clinical_recs = outputs["clinical_recs_df"]

    for name, df in {
        "df_syn_vec": synthetic,
        "patient_profiles_df": profiles,
        "clinical_recs_df": clinical_recs,
    }.items():
        if "patient_id" not in df.columns:
            raise AssertionError(
                f"{name} is missing required column 'patient_id'."
            )

    expected_ids = set(synthetic["patient_id"].dropna().astype(str))
    profile_ids = set(profiles["patient_id"].dropna().astype(str))
    recommendation_ids = set(
        clinical_recs["patient_id"].dropna().astype(str)
    )

    if profile_ids != expected_ids:
        raise AssertionError(
            "patient_profiles_df does not contain exactly the "
            "sample patient population."
        )

    if recommendation_ids != expected_ids:
        raise AssertionError(
            "clinical_recs_df does not contain all sample patients."
        )


def validate_recommendation_limits(
    outputs: Dict[str, pd.DataFrame],
    summary: Dict,
) -> None:
    """Validate top-N recommendation limits."""
    clinical_recs = outputs["clinical_recs_df"]

    master_config = summary.get("master_config", {})
    top_n = master_config.get("top_n")

    if not isinstance(top_n, int) or top_n <= 0:
        raise AssertionError(
            "master_config.top_n must be a positive integer."
        )

    counts = clinical_recs.groupby("patient_id").size()

    if (counts > top_n).any():
        offenders = counts[counts > top_n].to_dict()
        raise AssertionError(
            f"Patients exceed configured top_n={top_n}: {offenders}"
        )


def validate_rank_contract(
    outputs: Dict[str, pd.DataFrame],
) -> None:
    """Validate consecutive ranks for therapeutic recommendations."""
    clinical_recs = outputs["clinical_recs_df"]

    if "rank" not in clinical_recs.columns:
        raise AssertionError(
            "clinical_recs_df is missing required column 'rank'."
        )

    for patient_id, group in clinical_recs.groupby("patient_id"):
        ranks = pd.to_numeric(
            group["rank"],
            errors="coerce",
        ).dropna()

        if ranks.empty:
            continue

        actual = ranks.astype(int).tolist()
        expected = list(range(1, len(actual) + 1))

        if actual != expected:
            raise AssertionError(
                f"Invalid ranks for patient {patient_id}: "
                f"expected={expected}, actual={actual}"
            )


def validate_score_contract(
    outputs: Dict[str, pd.DataFrame],
) -> None:
    """Validate final scores for ranked therapeutic recommendations."""
    clinical_recs = outputs["clinical_recs_df"]

    required_cols = {"rank", "final_score"}
    missing = required_cols - set(clinical_recs.columns)

    if missing:
        raise AssertionError(
            f"clinical_recs_df missing score columns: {sorted(missing)}"
        )

    therapeutic_rows = clinical_recs["rank"].notna()

    scores = pd.to_numeric(
        clinical_recs.loc[therapeutic_rows, "final_score"],
        errors="coerce",
    )

    if scores.isna().any():
        raise AssertionError(
            "Ranked therapeutic recommendations contain missing "
            "or non-numeric final_score values."
        )

    if not np.isfinite(scores.to_numpy()).all():
        raise AssertionError(
            "Ranked therapeutic recommendations contain non-finite scores."
        )

    if not scores.between(0.0, 1.0).all():
        raise AssertionError(
            "Ranked therapeutic final_score values must be within [0, 1]."
        )


def validate_normotensive_contract(
    outputs: Dict[str, pd.DataFrame],
) -> None:
    """Validate no-treatment output for bundled normotensive patients."""
    clinical_recs = outputs["clinical_recs_df"]

    if "Maternal_Diagnosis" not in clinical_recs.columns:
        raise AssertionError(
            "clinical_recs_df is missing 'Maternal_Diagnosis'."
        )

    normotensive = clinical_recs[
        clinical_recs["Maternal_Diagnosis"] == "Normotensive"
    ].copy()

    if normotensive.empty:
        raise AssertionError(
            "Bundled sample run contains no normotensive output."
        )

    treatment_cols = [
        col
        for col in [
            "drug_1",
            "route_1",
            "dose_1",
            "drug_2",
            "route_2",
            "dose_2",
        ]
        if col in normotensive.columns
    ]

    if treatment_cols:
        if normotensive[treatment_cols].notna().any().any():
            raise AssertionError(
                "Normotensive output contains a treatment recommendation."
            )

    if "final_score" in normotensive.columns:
        if normotensive["final_score"].notna().any():
            raise AssertionError(
                "Normotensive output must not contain final_score."
            )

    if "rank" in normotensive.columns:
        if normotensive["rank"].notna().any():
            raise AssertionError(
                "Normotensive output must not contain rank."
            )

    if "clinical_alert" not in normotensive.columns:
        raise AssertionError(
            "Normotensive output is missing clinical_alert."
        )

    if normotensive["clinical_alert"].isna().any():
        raise AssertionError(
            "Normotensive output contains an empty clinical_alert."
        )


def validate_score_weights(summary: Dict) -> None:
    """Validate configured final-score weights."""
    config = summary.get("master_config", {})

    weight_names = [
        "similarity_weight",
        "efficiency_weight",
        "safety_weight",
    ]

    try:
        weights: List[float] = [
            float(config[name])
            for name in weight_names
        ]
    except (KeyError, TypeError, ValueError) as exc:
        raise AssertionError(
            "Master configuration does not contain valid score weights."
        ) from exc

    if any(weight < 0.0 for weight in weights):
        raise AssertionError(
            "Final-score weights cannot be negative."
        )

    if not np.isclose(sum(weights), 1.0):
        raise AssertionError(
            f"Final-score weights must sum to 1.0; got {sum(weights)}."
        )


def validate_sample_run(output_dir: Path) -> None:
    """Run all sample-output validation checks."""
    output_dir = Path(output_dir)

    if not output_dir.is_dir():
        raise FileNotFoundError(
            f"Output directory not found: {output_dir}"
        )

    validate_required_files(output_dir)

    outputs = load_outputs(output_dir)
    summary = load_summary(output_dir)

    validate_nonempty_outputs(outputs)
    validate_summary_shapes(outputs, summary)
    validate_patient_coverage(outputs)
    validate_recommendation_limits(outputs, summary)
    validate_rank_contract(outputs)
    validate_score_contract(outputs)
    validate_normotensive_contract(outputs)
    validate_score_weights(summary)


def build_parser() -> argparse.ArgumentParser:
    """Build CLI parser."""
    parser = argparse.ArgumentParser(
        description=(
            "Validate artifacts generated by the bundled "
            "end-to-end recommender sample run."
        )
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        required=True,
        help="Directory containing generated sample-run artifacts.",
    )
    return parser


def main() -> None:
    """CLI entrypoint."""
    args = build_parser().parse_args()

    validate_sample_run(args.output_dir)

    print("Sample recommender run validation passed.")
    print(f"  output directory: {args.output_dir}")


if __name__ == "__main__":
    main()
